-- 013_pattern2_bitemporal.sql
-- =============================================================================
-- Pattern 2: bitemporal dim infrastructure (per docs/001_append_only_redesign.md).
--
-- Pattern 1 (raw)  → uni-temporal: tracks "what we observed at time T"
-- Pattern 2 (dim)  → bitemporal:   tracks "what we knew at transaction-time T
--                                  about how things were at business-time B"
--
-- Use cases (app-authored data):
--   - Categorisations / mappings whose definition evolves
--   - Allocation targets / goals subject to retroactive correction
--   - Any taxonomy that can be renamed, merged, split, or future-dated
--
-- Schema shape (every dim table follows this):
--   id           uuid        DEFAULT gen_random_uuid()
--   revision     int         NOT NULL
--   created_at   timestamptz DEFAULT now()        -- transaction time
--   valid_from   timestamptz NOT NULL DEFAULT now() -- business time, opt-in retroactive
--   <typed content fields>
--   deleted      boolean     DEFAULT false
--   purged       boolean     DEFAULT false
--   PRIMARY KEY (id, revision)
--
-- valid_until / valid_to are NOT physical columns — derive via LEAD when
-- range projections are needed. Keeping append-only invariant.
--
-- Access pattern (per-table function generated by helper):
--   <table>_at(biz_t timestamptz DEFAULT now(), tx_t timestamptz DEFAULT now())
--     RETURNS SETOF <table>
--   "for each id, the revision visible at (biz_t, tx_t),
--    ordered by valid_from DESC then revision DESC"
--
-- Critical: ORDER BY uses valid_from DESC (not just revision DESC) so that
-- retroactive corrections describe the right business-time window. A higher
-- revision number means later observation, but its valid_from may be in the
-- past. The "current value at biz_t" is the row with the LATEST valid_from
-- that is still <= biz_t — among those, the highest revision wins (= latest
-- knowledge for that biz window).
-- =============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. Helper procedure: minted per-table _at functions
-- ---------------------------------------------------------------------------
-- Adding a new dim table is now a 2-step operation:
--   CREATE TABLE data_warehouse_v2.<name> ( ... Pattern 2 shape ... );
--   CALL data_warehouse_v2.create_dim_at_function('<name>');
-- The helper introspects nothing — it just generates the standard function
-- bound to the given table type. Re-running with the same name is a no-op
-- (CREATE OR REPLACE FUNCTION).

CREATE OR REPLACE PROCEDURE data_warehouse_v2.create_dim_at_function(tbl text)
LANGUAGE plpgsql AS $proc$
BEGIN
  EXECUTE format($sql$
    CREATE OR REPLACE FUNCTION data_warehouse_v2.%1$I_at(
      biz_t timestamptz DEFAULT now(),
      tx_t  timestamptz DEFAULT now()
    )
    RETURNS SETOF data_warehouse_v2.%1$I
    LANGUAGE SQL STABLE AS $func$
      SELECT DISTINCT ON (id) *
      FROM data_warehouse_v2.%1$I
      WHERE created_at <= tx_t
        AND valid_from <= biz_t
      ORDER BY id, valid_from DESC, revision DESC;
    $func$;

    COMMENT ON FUNCTION data_warehouse_v2.%1$I_at(timestamptz, timestamptz) IS
      'Bitemporal as-of-(biz_t, tx_t) snapshot. Per id, returns the revision '
      'with the latest valid_from <= biz_t observed by tx_t. Filter deleted / '
      'purged in the caller (see wrap_dim macro for the standard wrapper).';
  $sql$, tbl);
END $proc$;

COMMENT ON PROCEDURE data_warehouse_v2.create_dim_at_function(text) IS
  'Mints the per-table <tbl>_at(biz_t, tx_t) bitemporal access function. '
  'Call once after creating any Pattern 2 dim table.';

-- ---------------------------------------------------------------------------
-- 2. Demo table: example_dim (template for future dim tables)
-- ---------------------------------------------------------------------------
-- A minimal Pattern 2 table that exercises every facet of the design.
-- Replace `name` and `description` with domain-specific typed columns when
-- copying this shape.

CREATE TABLE data_warehouse_v2.example_dim (
    id           uuid        NOT NULL DEFAULT gen_random_uuid(),
    revision     int         NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    valid_from   timestamptz NOT NULL DEFAULT now(),
    -- typed content (replace per domain):
    name         text        NOT NULL,
    description  text,
    deleted      boolean     NOT NULL DEFAULT false,
    purged       boolean     NOT NULL DEFAULT false,
    PRIMARY KEY (id, revision)
);

CREATE UNIQUE INDEX example_dim_purge_unique
    ON data_warehouse_v2.example_dim (id) WHERE purged = true;

-- Index optimised for the standard at(biz_t, tx_t) lookup.
CREATE INDEX example_dim_id_validfrom_revision_desc
    ON data_warehouse_v2.example_dim (id, valid_from DESC, revision DESC);

COMMENT ON TABLE data_warehouse_v2.example_dim IS
  'Pattern 2 (bitemporal) demo / template. Real dim tables follow this exact '
  'shape with their own typed content columns in place of name/description.';

-- Mint the per-table access function:
CALL data_warehouse_v2.create_dim_at_function('example_dim');

-- ---------------------------------------------------------------------------
-- 3. Seed three retroactive scenarios to exercise the pattern
-- ---------------------------------------------------------------------------
-- Entity #1 ("Education"):
--   rev 1 (created 2026-01-01, valid_from 2026-01-01) name = "Education"
--   rev 2 (created 2026-03-01, valid_from 2026-03-01) name = "Education" (same name, content changed)
--   rev 3 (created 2026-05-01, valid_from 2026-02-15) name = "Study" (RETROACTIVE: "actually it was Study from Feb 15")
--
-- Entity #2 ("Drift" → soft-deleted):
--   rev 1 (created 2026-01-01, valid_from 2026-01-01) name = "Drift"
--   rev 2 (created 2026-05-01, valid_from 2026-05-01) deleted = true (delete effective May 1)
--
-- Entity #3 ("future-dated change"):
--   rev 1 (created 2026-04-01, valid_from 2026-04-01) name = "Original"
--   rev 2 (created 2026-04-15, valid_from 2026-06-01) name = "Renamed" (FUTURE-DATED: "from June 1")

INSERT INTO data_warehouse_v2.example_dim
    (id, revision, created_at, valid_from, name, description, deleted)
VALUES
    -- #1: Education with retroactive correction
    ('00000000-0000-0000-0000-000000000001', 1,
     '2026-01-01 00:00+09', '2026-01-01 00:00+09', 'Education', 'original definition', false),
    ('00000000-0000-0000-0000-000000000001', 2,
     '2026-03-01 09:00+09', '2026-03-01 00:00+09', 'Education', 'updated description', false),
    ('00000000-0000-0000-0000-000000000001', 3,
     '2026-05-01 09:00+09', '2026-02-15 00:00+09', 'Study',     'retroactive rename: was Study from Feb 15', false),

    -- #2: Drift then soft-deleted
    ('00000000-0000-0000-0000-000000000002', 1,
     '2026-01-01 00:00+09', '2026-01-01 00:00+09', 'Drift',     'original', false),
    ('00000000-0000-0000-0000-000000000002', 2,
     '2026-05-01 09:00+09', '2026-05-01 00:00+09', 'Drift',     'now deleted', true),

    -- #3: future-dated rename
    ('00000000-0000-0000-0000-000000000003', 1,
     '2026-04-01 00:00+09', '2026-04-01 00:00+09', 'Original',  'starting state', false),
    ('00000000-0000-0000-0000-000000000003', 2,
     '2026-04-15 00:00+09', '2026-06-01 00:00+09', 'Renamed',   'future-dated effective June 1', false);

COMMIT;

-- =============================================================================
-- Sanity-check queries (uncomment and run after COMMIT):
--
-- -- Entity #1 retroactive: at biz=2026-04-01 the truth is "Education" (rev 2),
-- -- because rev 3's valid_from (2026-02-15) is older than rev 2's (2026-03-01).
-- -- "Latest knowledge for the latest biz boundary <= biz_t" = rev 2 → Education.
-- SELECT id, name, valid_from, revision
-- FROM data_warehouse_v2.example_dim_at('2026-04-01+09'::timestamptz)
-- WHERE id = '00000000-0000-0000-0000-000000000001' AND deleted = false;
--   -- expected: name=Education, revision=2
--
-- -- Same entity at biz=2026-02-20: rev 2 is excluded (valid_from > 2026-02-20),
-- -- rev 3 (Study, valid_from 2026-02-15) wins over rev 1 (Education, valid_from 2026-01-01).
-- SELECT id, name, valid_from, revision
-- FROM data_warehouse_v2.example_dim_at('2026-02-20+09'::timestamptz)
-- WHERE id = '00000000-0000-0000-0000-000000000001' AND deleted = false;
--   -- expected: name=Study, revision=3
--
-- -- Transaction-time slice: what did we know at tx=2026-03-15 about biz=2026-02-20?
-- -- rev 3 wasn't created until 2026-05-01, so it's filtered out → rev 1 wins.
-- SELECT id, name, revision
-- FROM data_warehouse_v2.example_dim_at('2026-02-20+09'::timestamptz, '2026-03-15+09'::timestamptz)
-- WHERE id = '00000000-0000-0000-0000-000000000001' AND deleted = false;
--   -- expected: name=Education, revision=1
--
-- -- Future-dated: at biz=2026-05-01 the rename hasn't taken effect yet.
-- SELECT id, name, valid_from FROM data_warehouse_v2.example_dim_at('2026-05-01+09'::timestamptz)
-- WHERE id = '00000000-0000-0000-0000-000000000003' AND deleted = false;
--   -- expected: name=Original
--
-- -- Same entity at biz=2026-06-15 (after the future-dated valid_from):
-- SELECT id, name, valid_from FROM data_warehouse_v2.example_dim_at('2026-06-15+09'::timestamptz)
-- WHERE id = '00000000-0000-0000-0000-000000000003' AND deleted = false;
--   -- expected: name=Renamed
--
-- -- Soft-delete visibility: at biz=2026-04-01 (before delete), entity #2 is alive.
-- SELECT id, name, deleted FROM data_warehouse_v2.example_dim_at('2026-04-01+09'::timestamptz)
-- WHERE id = '00000000-0000-0000-0000-000000000002';
--   -- expected: name=Drift, deleted=false
--
-- -- At biz=2026-06-01 (after delete), entity #2 is tombstoned.
-- SELECT id, name, deleted FROM data_warehouse_v2.example_dim_at('2026-06-01+09'::timestamptz)
-- WHERE id = '00000000-0000-0000-0000-000000000002';
--   -- expected: name=Drift, deleted=true
-- =============================================================================
